FROM mcr.microsoft.com/devcontainers/base:ubuntu
RUN apt update && apt upgrade -y
# RUN apt install build-essential procps curl file; NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    